apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-chown
  namespace: kube-system
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: grafana-chown
          command: ["chown", "-R", "472:472", "/var/lib/grafana"]
          image: busybox
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: grafana-persistent-storage
              subPath: grafana
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-persistent-storage
          persistentVolumeClaim:
            claimName: grafana

