apiVersion: v1
appVersion: 2.2.0
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: http://traefik.io/traefik.logo.png
keywords:
- traefik
- ingress
maintainers:
- email: emile@vauge.com
  name: emilevauge
- email: daniel.tomcej@gmail.com
  name: dtomcej
- email: ludovic@containo.us
  name: ldez
name: traefik
sources:
- https://github.com/containous/traefik
version: 8.0.3
